from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

from domain.models import DagNode, WorkflowGraph

from .expressions import rewrite_job_expressions
from .graph import GENERATED_PREFIX, GENERATOR_VERSION, _generated_workflow_filename
from .loader import load_yaml

GENERATED_HEADER = """# Code generated by ci-scheduler workflow-gen. DO NOT EDIT.
# Source: {source_path}
# Source job: {source_job}
# Generator version: {version}
# Source hash: {source_hash}
"""


def _output_publication_steps(
    dispatch_id_expr: str,
    declared_outputs: dict[str, Any],
) -> list[dict[str, Any]]:
    output_names = list(declared_outputs)
    output_env = {
        "SCHEDULER_OUTPUT_NAMES": json.dumps(output_names, separators=(",", ":")),
    }
    for index, name in enumerate(output_names):
        expression = declared_outputs[name]
        if not isinstance(expression, str):
            raise ValueError(f"job output {name!r} must be a string expression")
        output_env[f"SCHEDULER_OUTPUT_{index}"] = expression

    return [
        {
            "name": "Publish scheduler outputs",
            "if": "always()",
            "shell": "bash",
            "env": output_env,
            "run": (
                "set -euo pipefail\n"
                "python - <<'PY'\n"
                "import json, os, pathlib\n"
                "names = json.loads(os.environ['SCHEDULER_OUTPUT_NAMES'])\n"
                "outputs = {\n"
                "    name: os.environ.get(f'SCHEDULER_OUTPUT_{index}', '')\n"
                "    for index, name in enumerate(names)\n"
                "}\n"
                "path = pathlib.Path('scheduler-outputs.json')\n"
                "path.write_text(json.dumps({'version': 1, 'outputs': outputs}, sort_keys=True))\n"
                "print(f'Wrote {path} with {len(outputs)} outputs')\n"
                "PY"
            ),
        },
        {
            "name": "Upload scheduler outputs artifact",
            "if": "always()",
            "uses": "actions/upload-artifact@v4",
            "with": {
                "name": dispatch_id_expr,
                "path": "scheduler-outputs.json",
                "if-no-files-found": "ignore",
            },
        },
    ]


def _trusted_checkout_steps() -> list[dict[str, Any]]:
    return [
        {
            "name": "Checkout trusted orchestration",
            "uses": "actions/checkout@v4",
            "with": {
                "ref": "${{ github.event.repository.default_branch }}",
                "path": "trusted-orchestration",
                "sparse-checkout": "ci-scheduler",
            },
        },
        {
            "name": "Checkout PR source",
            "uses": "actions/checkout@v4",
            "with": {
                "ref": "${{ inputs.head_sha }}",
            },
        },
    ]


def generate_workflow(
    graph: WorkflowGraph,
    node: DagNode,
    *,
    repo_default_branch: str = "main",
) -> dict[str, Any]:
    if not node.is_executable or node.generated_workflow_path is None:
        raise ValueError(f"node {node.key} is not executable")

    source_data = load_yaml(Path(node.source_path))
    workflow_name = str(source_data.get("name", graph.root_workflow))
    need_key_map = {
        graph.get(dependency).job_id: dependency
        for dependency in graph.needs(node.key)
    }
    job = rewrite_job_expressions(
        dict(node.job_def),
        job_key=node.key,
        need_key_map=need_key_map,
    )
    source_outputs = job.get("outputs") or {}
    if not isinstance(source_outputs, dict):
        raise ValueError(f"job {node.key} outputs must be a mapping")

    copied_fields = (
        "name",
        "runs-on",
        "timeout-minutes",
        "container",
        "services",
        "permissions",
        "environment",
        "defaults",
        "outputs",
    )
    generated_job: dict[str, Any] = {}
    for field in copied_fields:
        if field in job:
            generated_job[field] = job[field]

    steps = list(job.get("steps") or [])
    generated_job["steps"] = (
        _trusted_checkout_steps()
        + steps
        + _output_publication_steps("${{ inputs.dispatch_id }}", source_outputs)
    )

    return {
        "name": f"Scheduler / {workflow_name} / {job.get('name', node.job_id)}",
        "run-name": (
            "scheduler dispatch-${{ inputs.dispatch_id }} "
            "queue-item-${{ inputs.queue_item_id }}"
        ),
        "on": {
            "workflow_dispatch": {
                "inputs": {
                    "queue_item_id": {"required": True, "type": "string"},
                    "dispatch_id": {"required": True, "type": "string"},
                    "pr_number": {"required": True, "type": "string"},
                    "head_sha": {"required": True, "type": "string"},
                    "attempt": {"required": True, "type": "string"},
                    "scheduler_context": {"required": True, "type": "string"},
                    "source_hash": {"required": True, "type": "string"},
                }
            }
        },
        "permissions": source_data.get("permissions", {"contents": "read"}),
        "env": rewrite_job_expressions(
            {"env": source_data.get("env", {})},
            job_key=node.key,
            need_key_map=need_key_map,
        )["env"],
        "jobs": {
            "run-stage": generated_job,
        },
    }


def render_workflow_yaml(
    graph: WorkflowGraph,
    node: DagNode,
) -> str:
    payload = generate_workflow(graph, node)
    header = GENERATED_HEADER.format(
        source_path=graph.source_path,
        source_job=node.job_id,
        version=GENERATOR_VERSION,
        source_hash=graph.source_hash,
    )
    return header + "\n" + yaml.dump(payload, sort_keys=False, default_flow_style=False)


def generate_all(
    graph: WorkflowGraph,
    output_dir: Path,
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for node in graph.executable_nodes():
        if node.generated_workflow_path is None:
            continue
        filename = _generated_workflow_filename(node.key)
        path = output_dir / filename
        path.write_text(render_workflow_yaml(graph, node), encoding="utf-8")
        written.append(path)
    return written


def check_generated(
    graph: WorkflowGraph,
    output_dir: Path,
) -> list[str]:
    errors: list[str] = []
    for node in graph.executable_nodes():
        if node.generated_workflow_path is None:
            continue
        filename = _generated_workflow_filename(node.key)
        path = output_dir / filename
        if not path.exists():
            errors.append(f"missing generated workflow: {path}")
            continue
        expected = render_workflow_yaml(graph, node)
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"generated workflow drift: {path}")
    return errors
