from __future__ import annotations

from pathlib import Path

from compiler.expressions import rewrite_expression, rewrite_job_expressions
from compiler.graph import compile_workflow
from compiler.generator import check_generated, generate_all


REPO_ROOT = Path(__file__).resolve().parents[2]
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"
GENERATED_DIR = WORKFLOWS_DIR / "generated"


def test_compile_omni_ci_dag_has_virtual_reusable_nodes() -> None:
    graph = compile_workflow(WORKFLOWS_DIR / "omni-ci.yaml", workflows_dir=WORKFLOWS_DIR)
    virtual = [node for node in graph.nodes if node.is_virtual]
    assert {node.key for node in virtual} == {
        "omni-ci::asr-ci",
        "omni-ci::tts-ci",
        "omni-ci::qwen3-omni-ci",
        "omni-ci::pr-test",
    }
    asr_stage_1 = graph.get("omni-ci::asr-ci/test-asr-ci::stage-1-multi-speaker")
    assert "omni-ci::setup" in asr_stage_1.needs
    assert "omni-ci::pr-test" in asr_stage_1.needs


def test_rewrite_needs_result_expression() -> None:
    result = rewrite_expression(
        "always() && needs.setup.result == 'success'",
        job_key_prefix="omni-ci",
    )
    assert "fromJSON(inputs.scheduler_context).needs['omni-ci::setup'].result" in result.expression
    assert result.classification == "rewritten"


def test_rewrite_pr_context_expression() -> None:
    result = rewrite_expression(
        "github.event.pull_request.number == 100",
        job_key_prefix="omni-ci",
    )
    assert "fromJSON(inputs.scheduler_context).source_event.number" in result.expression


def test_rewrite_cross_run_references_in_nested_job_fields() -> None:
    rewritten = rewrite_job_expressions(
        {
            "env": {
                "LABELS": "${{ needs.preflight.outputs.labels || '[]' }}",
            },
            "steps": [
                {
                    "uses": "actions/checkout@v4",
                    "with": {"ref": "${{ github.event.pull_request.head.sha }}"},
                }
            ],
        },
        job_key="omni-ci::pick-tts-model",
        need_key_map={"preflight": "omni-ci::preflight"},
    )

    assert "needs['omni-ci::preflight'].outputs.labels" in rewritten["env"]["LABELS"]
    assert "source_event.head.sha" in rewritten["steps"][0]["with"]["ref"]


def test_generator_emits_dispatch_contract(tmp_path: Path) -> None:
    graph = compile_workflow(WORKFLOWS_DIR / "omni-ci.yaml", workflows_dir=WORKFLOWS_DIR)
    setup = graph.get("omni-ci::setup")
    generate_all(graph, tmp_path)
    generated = tmp_path / Path(setup.generated_workflow_path or "").name
    text = generated.read_text(encoding="utf-8")
    assert "Code generated by ci-scheduler workflow-gen. DO NOT EDIT." in text
    assert "Source: .github/workflows/omni-ci.yaml" in text
    assert "queue_item_id:" in text
    assert "scheduler_context:" in text
    assert "Publish scheduler outputs" in text
    assert "queue-item-${{ inputs.queue_item_id" in text
    assert check_generated(graph, tmp_path) == []


def test_generator_exports_declared_job_outputs(tmp_path: Path) -> None:
    graph = compile_workflow(WORKFLOWS_DIR / "omni-ci.yaml", workflows_dir=WORKFLOWS_DIR)
    pick = graph.get("omni-ci::pick-tts-model")
    generate_all(graph, tmp_path)
    generated = tmp_path / Path(pick.generated_workflow_path or "").name
    text = generated.read_text(encoding="utf-8")

    assert "SCHEDULER_OUTPUT_NAMES: '[\"tts_ci_model\"]'" in text
    assert "SCHEDULER_OUTPUT_0: ${{ steps.pick.outputs.tts_ci_model }}" in text
    assert "needs['omni-ci::preflight'].outputs.labels" in text
