# SPDX-License-Identifier: Apache-2.0
"""CosyVoice vocoder for MiniCPM-o 2.6 audio output.

This module provides CosyVoice flow-matching vocoder integration for
converting LLM-generated audio tokens back to PCM waveform.

CosyVoice is used in MiniCPM-o 2.6 for speech synthesis, taking audio
codes generated by the LLM and reconstructing them into natural speech.

Reference: https://github.com/FunAudioLLM/CosyVoice
"""

from __future__ import annotations

import logging
import os
import time
from dataclasses import dataclass, field
from typing import Any

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)

# Default sample rate for CosyVoice output
COSYVOICE_SAMPLE_RATE = 22050

# Audio token special markers (MiniCPM-o specific)
AUDIO_START_TOKEN = "<|audio_start|>"
AUDIO_END_TOKEN = "<|audio_end|>"
AUDIO_PAD_TOKEN = "<|audio_pad|>"


@dataclass
class CosyVoiceConfig:
    """Configuration for CosyVoice vocoder."""

    model_path: str
    sample_rate: int = COSYVOICE_SAMPLE_RATE
    device: str = "cuda"
    dtype: torch.dtype = torch.float32
    # Flow-matching inference parameters
    flow_steps: int = 10
    temperature: float = 1.0
    # Streaming parameters
    chunk_size: int = 50  # tokens per chunk for streaming


@dataclass
class VocoderOutput:
    """Output from the CosyVoice vocoder."""

    audio_samples: torch.Tensor  # [T] waveform
    sample_rate: int
    duration_s: float = 0.0
    # Metadata
    input_tokens: int = 0
    inference_time_s: float = 0.0


def load_cosyvoice_model(
    model_path: str,
    *,
    device: str = "cuda",
    dtype: torch.dtype | None = None,
) -> tuple[Any, CosyVoiceConfig]:
    """Load CosyVoice model from checkpoint.

    Args:
        model_path: Path to CosyVoice model checkpoint or HuggingFace repo
        device: Target device for model
        dtype: Model dtype (default: float32 for vocoder quality)

    Returns:
        Tuple of (model, config)
    """
    if dtype is None:
        dtype = torch.float32

    # Resolve model path (local or HuggingFace)
    if os.path.isdir(model_path):
        checkpoint_dir = model_path
    else:
        try:
            from huggingface_hub import snapshot_download

            checkpoint_dir = snapshot_download(model_path)
        except Exception as e:
            raise ValueError(f"Cannot resolve CosyVoice model path: {model_path}") from e

    logger.info("Loading CosyVoice vocoder from %s ...", checkpoint_dir)
    t0 = time.perf_counter()

    # Try to load CosyVoice2 model first, fallback to CosyVoice
    try:
        from cosyvoice.cli.cosyvoice import CosyVoice2

        model = CosyVoice2(checkpoint_dir, load_jit=False, load_onnx=False)
        logger.info("Loaded CosyVoice2 model")
    except ImportError:
        try:
            from cosyvoice.cli.cosyvoice import CosyVoice

            model = CosyVoice(checkpoint_dir, load_jit=False, load_onnx=False)
            logger.info("Loaded CosyVoice model")
        except ImportError as e:
            raise ImportError(
                "CosyVoice is required for MiniCPM-o audio output. "
                "Install with: pip install cosyvoice"
            ) from e

    # Move flow model to target device
    if hasattr(model, "model") and hasattr(model.model, "to"):
        model.model.to(device=device, dtype=dtype)

    config = CosyVoiceConfig(
        model_path=checkpoint_dir,
        device=device,
        dtype=dtype,
    )

    logger.info("CosyVoice vocoder loaded in %.2fs", time.perf_counter() - t0)
    return model, config


class CosyVoiceVocoder(nn.Module):
    """CosyVoice vocoder wrapper for MiniCPM-o 2.6.

    This module wraps the CosyVoice flow-matching model to convert
    audio tokens generated by MiniCPM-o LLM into PCM waveform.

    The vocoder supports both batch and streaming modes:
    - Batch mode: Process all audio tokens at once
    - Streaming mode: Process tokens incrementally with overlapping windows
    """

    def __init__(
        self,
        model_path: str,
        *,
        device: str = "cuda",
        dtype: torch.dtype | None = None,
    ) -> None:
        super().__init__()
        self._model, self._config = load_cosyvoice_model(
            model_path, device=device, dtype=dtype
        )
        self._device = device
        self._dtype = dtype or torch.float32
        # Cache for streaming
        self._stream_cache: dict[str, Any] = {}

    @property
    def sample_rate(self) -> int:
        """Output sample rate."""
        return self._config.sample_rate

    @property
    def device(self) -> str:
        """Model device."""
        return self._device

    def _extract_audio_tokens(
        self,
        output_ids: torch.Tensor | list[int],
        *,
        audio_start_id: int | None = None,
        audio_end_id: int | None = None,
    ) -> torch.Tensor | None:
        """Extract audio token sequence from LLM output.

        The LLM output may contain interleaved text and audio tokens.
        This method extracts only the audio tokens between audio_start
        and audio_end markers.

        Args:
            output_ids: Full LLM output token sequence
            audio_start_id: Token ID for audio start marker
            audio_end_id: Token ID for audio end marker

        Returns:
            Audio token tensor [num_audio_tokens] or None if no audio found
        """
        if isinstance(output_ids, list):
            output_ids = torch.tensor(output_ids, dtype=torch.long)

        if audio_start_id is None or audio_end_id is None:
            # No markers, assume all tokens are audio (fallback)
            return output_ids

        # Find audio segments
        audio_tokens = []
        in_audio = False
        for token_id in output_ids.tolist():
            if token_id == audio_start_id:
                in_audio = True
                continue
            if token_id == audio_end_id:
                in_audio = False
                continue
            if in_audio:
                audio_tokens.append(token_id)

        if not audio_tokens:
            return None

        return torch.tensor(audio_tokens, dtype=torch.long)

    def forward(
        self,
        audio_codes: torch.Tensor,
        *,
        speaker_embedding: torch.Tensor | None = None,
    ) -> VocoderOutput:
        """Convert audio codes to waveform.

        Args:
            audio_codes: Audio token tensor [num_tokens] or [batch, num_tokens]
            speaker_embedding: Optional speaker embedding for voice cloning

        Returns:
            VocoderOutput with generated audio
        """
        t0 = time.perf_counter()

        if audio_codes.ndim == 1:
            audio_codes = audio_codes.unsqueeze(0)

        num_tokens = audio_codes.shape[-1]
        audio_codes = audio_codes.to(device=self._device)

        # Use CosyVoice flow-matching decoder
        with torch.no_grad():
            # CosyVoice API expects specific input format
            # This may need adjustment based on actual CosyVoice version
            if hasattr(self._model, "decode"):
                # CosyVoice2 style
                audio = self._model.decode(
                    audio_codes,
                    flow_steps=self._config.flow_steps,
                )
            elif hasattr(self._model, "inference_cross_lingual"):
                # CosyVoice style - use token2wav
                audio = self._model.token2wav(
                    audio_codes,
                    speed=1.0,
                )
            else:
                raise RuntimeError("Unsupported CosyVoice model version")

        # Ensure output shape is [T]
        if isinstance(audio, torch.Tensor):
            audio_samples = audio.squeeze().float().cpu()
        else:
            # Handle generator output from CosyVoice
            audio_chunks = list(audio)
            if audio_chunks:
                audio_samples = torch.cat(
                    [chunk["tts_speech"].squeeze().cpu() for chunk in audio_chunks],
                    dim=-1,
                ).float()
            else:
                audio_samples = torch.zeros(0)

        duration_s = audio_samples.shape[-1] / self.sample_rate if audio_samples.numel() > 0 else 0.0
        inference_time = time.perf_counter() - t0

        return VocoderOutput(
            audio_samples=audio_samples,
            sample_rate=self.sample_rate,
            duration_s=duration_s,
            input_tokens=num_tokens,
            inference_time_s=inference_time,
        )

    def vocode_from_llm_output(
        self,
        output_ids: torch.Tensor | list[int],
        *,
        tokenizer: Any = None,
    ) -> VocoderOutput | None:
        """Convert LLM output to audio, extracting audio tokens automatically.

        Args:
            output_ids: Full LLM output sequence
            tokenizer: Tokenizer for resolving special token IDs

        Returns:
            VocoderOutput or None if no audio tokens found
        """
        audio_start_id = None
        audio_end_id = None

        if tokenizer is not None:
            # Try to get audio token IDs from tokenizer
            vocab = getattr(tokenizer, "get_vocab", lambda: {})()
            audio_start_id = vocab.get(AUDIO_START_TOKEN)
            audio_end_id = vocab.get(AUDIO_END_TOKEN)

        audio_codes = self._extract_audio_tokens(
            output_ids,
            audio_start_id=audio_start_id,
            audio_end_id=audio_end_id,
        )

        if audio_codes is None or audio_codes.numel() == 0:
            return None

        return self.forward(audio_codes)

    def reset_stream(self, request_id: str) -> None:
        """Reset streaming state for a request."""
        self._stream_cache.pop(request_id, None)

    def vocode_streaming(
        self,
        request_id: str,
        audio_codes: torch.Tensor,
        is_final: bool = False,
    ) -> VocoderOutput | None:
        """Incremental vocoding for streaming.

        Accumulates audio tokens and generates audio in chunks for
        low-latency streaming output.

        Args:
            request_id: Unique request identifier
            audio_codes: New audio tokens to add
            is_final: Whether this is the final chunk

        Returns:
            VocoderOutput for this chunk or None if not enough tokens
        """
        if request_id not in self._stream_cache:
            self._stream_cache[request_id] = {
                "tokens": [],
                "emitted_samples": 0,
            }

        cache = self._stream_cache[request_id]
        cache["tokens"].extend(audio_codes.tolist())

        # Check if we have enough tokens for a chunk
        total_tokens = len(cache["tokens"])
        chunk_size = self._config.chunk_size

        if not is_final and total_tokens < chunk_size:
            return None

        # Generate audio for all accumulated tokens
        all_codes = torch.tensor(cache["tokens"], dtype=torch.long)
        output = self.forward(all_codes)

        # Compute delta (new samples only)
        emitted = cache["emitted_samples"]
        total_samples = output.audio_samples.shape[-1]

        if total_samples <= emitted:
            return None

        delta_audio = output.audio_samples[emitted:]
        cache["emitted_samples"] = total_samples

        if is_final:
            self.reset_stream(request_id)

        return VocoderOutput(
            audio_samples=delta_audio,
            sample_rate=output.sample_rate,
            duration_s=delta_audio.shape[-1] / output.sample_rate,
            input_tokens=total_tokens,
            inference_time_s=output.inference_time_s,
        )
