# SPDX-License-Identifier: Apache-2.0
"""YuE2 defaults."""

DEFAULT_STYLE = "instrumental"
DEFAULT_COT = "full"
DEFAULT_SEED = 831001
DEFAULT_ABC_MAX_TOKENS = 4096
DEFAULT_SEMANTIC_MAX_TOKENS = 9000
DEFAULT_ODE_STEPS = 32
DEFAULT_VAE_CORE_FRAMES = 1024
DEFAULT_VAE_HALO_FRAMES = 16
OUTPUT_SAMPLE_RATE = 48000
OUTPUT_CHANNELS = 2
CONTEXT_TOKENS = 24576

__all__ = [
    "DEFAULT_STYLE",
    "DEFAULT_COT",
    "DEFAULT_SEED",
    "DEFAULT_ABC_MAX_TOKENS",
    "DEFAULT_SEMANTIC_MAX_TOKENS",
    "DEFAULT_ODE_STEPS",
    "DEFAULT_VAE_CORE_FRAMES",
    "DEFAULT_VAE_HALO_FRAMES",
    "OUTPUT_SAMPLE_RATE",
    "OUTPUT_CHANNELS",
    "CONTEXT_TOKENS",
]
