# SPDX-License-Identifier: Apache-2.0
"""Stable inference-contract constants for MiniMax Music 3."""

DEFAULT_MAX_AUDIO_FRAMES = 9_000
MAX_AUDIO_FRAMES = 9_000
MAX_PROMPT_TOKENS = 5_000

AR_HIDDEN_SIZE = 4_096 * 8
AR_CHUNK_FRAMES = 200
AR_CHUNK_HOP_FRAMES = 100

DEFAULT_DIT_STEPS = 30
DEFAULT_DIT_CFG_SCALE = 1.7
AR_CFG_SCALE = 1.5
AR_CFG_TOP_K = 50
SUPPORTED_ACOUSTIC_DTYPES = frozenset({"float32", "bfloat16"})

DAV_SAMPLE_RATE = 44_100
OUTPUT_SAMPLE_RATE = 32_000


__all__ = [
    "AR_CHUNK_FRAMES",
    "AR_CHUNK_HOP_FRAMES",
    "AR_HIDDEN_SIZE",
    "DAV_SAMPLE_RATE",
    "AR_CFG_SCALE",
    "AR_CFG_TOP_K",
    "DEFAULT_DIT_CFG_SCALE",
    "DEFAULT_DIT_STEPS",
    "DEFAULT_MAX_AUDIO_FRAMES",
    "MAX_AUDIO_FRAMES",
    "MAX_PROMPT_TOKENS",
    "OUTPUT_SAMPLE_RATE",
    "SUPPORTED_ACOUSTIC_DTYPES",
]
