# SPDX-License-Identifier: Apache-2.0
"""Shared request-size and timing limits for speech serving transports."""

MAX_VOICE_UPLOAD_BYTES = 10 * 1024 * 1024
_VOICE_UPLOAD_MULTIPART_OVERHEAD_BYTES = 64 * 1024
MAX_VOICE_UPLOAD_BODY_BYTES = (
    MAX_VOICE_UPLOAD_BYTES + _VOICE_UPLOAD_MULTIPART_OVERHEAD_BYTES
)

MAX_REFERENCE_AUDIO_BYTES = 10 * 1024 * 1024
_BASE64_ENCODED_REFERENCE_AUDIO_BYTES = ((MAX_REFERENCE_AUDIO_BYTES + 2) // 3) * 4

SPEECH_WS_CONFIG_TIMEOUT_S = 10.0
MAX_SPEECH_WS_CONFIG_MESSAGE_BYTES = _BASE64_ENCODED_REFERENCE_AUDIO_BYTES + 1024 * 1024
MAX_SPEECH_WS_TEXT_MESSAGE_BYTES = 128 * 1024
