# SPDX-License-Identifier: Apache-2.0
# Full Cosmos3-Super BF16 T2I on one 80 GB GPU. The 64B checkpoint is larger
# than device memory, so the native runtime streams DiT layers from host RAM.
config_cls: Cosmos3PipelineConfig
name: cosmos3-super-t2i-1xa100-bf16
model_path: nvidia/Cosmos3-Super@fe77b66696d645f663b8f27e942b3b43e4629e23

stages:
  generation:
    gpu: 0
    runtime_gpu_ids: [0]
    factory:
      output_dir: outputs/cosmos3_super
      server_args_overrides:
        performance_mode: memory
        warmup_mode: "off"
        attention_backend: torch_sdpa
        enable_torch_compile: false
        layerwise_offload_components: [dit]
        dit_layerwise_resident_layers: 24
