config_cls: HiggsTtsPipelineConfig
model_path: boson-sglang/higgs-audio-v3-tts-4b-base
relay_backend: shm
stages:
  - name: preprocessing
    process: pipeline
    factory: sglang_omni.models.higgs_tts.stages.create_preprocessing_executor
    next: audio_encoder
  - name: audio_encoder
    process: pipeline
    factory: sglang_omni.models.higgs_tts.stages.create_audio_encoder_executor
    factory_args:
      device: cuda
    gpu: 0
    next: tts_engine
  - name: tts_engine
    process: pipeline
    factory: sglang_omni.models.higgs_tts.stages.create_sglang_tts_engine_executor
    factory_args:
      device: cuda
      max_new_tokens: 2048
      server_args_overrides:
        disable_cuda_graph: true
    gpu: 0
    next: vocoder
  - name: vocoder
    process: pipeline
    factory: sglang_omni.models.higgs_tts.stages.create_vocoder_executor
    factory_args:
      device: cuda
    gpu: 0
    terminal: true
