config_cls: S2ProPipelineConfig
model_path: fishaudio/s2-pro
relay_backend: shm
stages:
  - name: preprocessing
    executor:
      factory: sglang_omni.models.fishaudio_s2_pro.pipeline.stages.create_preprocessing_executor
      args: {}
    get_next: sglang_omni.models.fishaudio_s2_pro.pipeline.next_stage.preprocessing_next
    relay:
      device: cpu
  - name: tts_engine
    executor:
      factory: sglang_omni.models.fishaudio_s2_pro.pipeline.stages.create_sglang_tts_engine_executor
      args:
        device: "cuda:0"
        max_new_tokens: 2048
        compile_level: partial
    get_next: sglang_omni.models.fishaudio_s2_pro.pipeline.next_stage.tts_engine_next
    relay:
      device: cuda
  - name: vocoder
    executor:
      factory: sglang_omni.models.fishaudio_s2_pro.pipeline.stages.create_vocoder_executor
      args: {}
    get_next: sglang_omni.models.fishaudio_s2_pro.pipeline.next_stage.vocoder_next
    relay:
      device: cpu
